# Generated by Django 4.2 on 2023-11-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='answer4',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='answer5',
            field=models.TextField(default=None),
        ),
    ]
