# Generated by Django 4.2 on 2023-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_question_answer_question_answer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.TextField(default='Не выполнено!'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.TextField(default='Не выполнено!'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.TextField(default='Не выполнено!'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.TextField(default='Не выполнено!'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer5',
            field=models.TextField(default='Не выполнено!'),
        ),
    ]
